name: Build and deploy ASP.Net Core app to Azure Web App - PhotoPix

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release ./Path/To/Project1.csproj
             dotnet build --configuration Release ./Path/To/Project2.csproj
             # Add more 'dotnet build' commands for each project in your solution

      - name: dotnet publish
        run: |
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp1 ./Path/To/Project1.csproj
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp2 ./Path/To/Project2.csproj
          # Add more 'dotnet publish' commands for each project in your solution

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp1
          # Adjust the path to the published output of your project

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F3100AFCE5FF4CFA982338BA19BC4A8B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_29747759B75F44B88503F0ADAF92339F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3D3084601E524F198B4CC9532F081823 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'PhotoPix'
          slot-name: 'Production'
          package: .
